### PR TITLE
add 'rabbitmq' to Brewfile

### PR DESCRIPTION
**Pull request by artemave**

### CODE REVIEW

**Comment by dalizard** [comment]
The RabbitMQ is mentioned [here](https://github.com/FundingCircle/funding_circle_app#prerequisites). I think we should definitely add all dependencies in the *Brewfile*, but also update the documentation accordingly.

**Comment by artemave** [comment]
@dalizard I am in compiling a pr that removes it from there. But that means that it needs to be here first. Catch 22?

**Comment by dalizard** [comment]
@artemave Yes. The *brewfiles* repo needs to install external dependencies.

**Comment by artemave** [comment]
Yeah, hence this pr needs to go first so I can back up removing `brew install rabbitmq` from the README of funding_circle_app.

**Comment by sldblog** [comment]
LGTM :+1:

**Pull request merged**
